# Generated by Django 6.0.5 on 2026-05-11 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Stol',
                'verbose_name_plural': 'Stollar',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Ofitsant',
                'verbose_name_plural': 'Ofitsantlar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Mobil platformadagi buyurtma identifikatori.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilingan'), ('partially_rejected', 'Qisman rad etilgan'), ('completed', 'Yakunlangan')], default='new', max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.diningtable')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.waiter')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.product')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
    ]
