# Generated by Django 6.0.5 on 2026-05-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_create_staff_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_number',
            field=models.PositiveSmallIntegerField(default=1, help_text="Stoldagi shot raqami (1-10). Bitta stolda bir nechta shot bo'lishi mumkin."),
        ),
    ]
