# Generated by Django 6.0.5 on 2026-05-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_printed',
            field=models.BooleanField(default=False, help_text='Oshxona cheki avtomatik chop etilgan-etilmagani.'),
        ),
    ]
