# Generated by Django 6.0.5 on 2026-06-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_kitchen_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Profil rasmi (ofitsant/direktor o'zi yuklaydi).", null=True, upload_to='avatars/'),
        ),
    ]
